In [1]:
import pandas as pd
import os
from tqdm import trange
import numpy as np
from sklearn.utils import shuffle

In [2]:
li=os.listdir()
li=sorted(li)[1:-1]

In [3]:
li

['1.csv',
 '2.csv',
 '3.csv',
 '4.csv',
 '5.csv',
 '6.csv',
 '7.csv',
 '8.csv',
 '90.csv',
 '91.csv',
 '92.csv',
 '93.csv',
 '94.csv']

In [4]:
lis_data={}
columns=[]
for i in li:
    df=pd.read_csv('./'+i,header=None)
    column=df.iloc(0)
    lis_data[int(i[:-4])]=df.drop([0],axis=1)[1:]
for i in column[0]:
    columns.append(i)

In [5]:
columns
columns_num=[1,2,3,4]

In [6]:
lis_data[1]

1       2      3      4
1     56.32  115.46  43.99  15.59
2     64.01  119.89  33.24   9.19
3      73.7  140.86   33.8   9.87
4      76.6  155.77  35.73  14.89
5     74.92  159.18   37.6  14.38
...     ...     ...    ...    ...
1884  58.94  125.91   4.09  18.47
1885  51.69  109.53   4.58  11.71
1886  56.56  123.68    5.5   10.2
1887  65.25  135.06    7.1     12
1888  75.41  159.06   8.15  19.41

[1888 rows x 4 columns]

In [7]:
for i in li[:7]:
    for c in columns_num:
        print(i[:-4],' ',c,' ',(lis_data[int(i[:-4])][c]=='None').sum())


1   1   27
1   2   31
1   3   27
1   4   27
2   1   29
2   2   24
2   3   19
2   4   18
3   1   1631
3   2   1631
3   3   1631
3   4   1631
4   1   10
4   2   10
4   3   11
4   4   12
5   1   45
5   2   43
5   3   94
5   4   39
6   1   1612
6   2   1612
6   3   1612
6   4   1613
7   1   1635
7   2   1631
7   3   1629
7   4   1630


### Planning to remove the data with more none values and replacing the remaining with the average value of a row a above and below

#### datas with more none values : 3,6,7,8,90,91,92,93

In [8]:
lis_data[3]=lis_data[3][1606:]
lis_data[6]=lis_data[6][1606:]
lis_data[7]=lis_data[7][1613:]
lis_data[8]=lis_data[8][1606:]
lis_data[90]=lis_data[90][1606:]
lis_data[91]=lis_data[91][1606:]
lis_data[92]=lis_data[92][1613:]
lis_data[93]=lis_data[93][1606:]

### Checking again if there are more none values in the processed data and proceeding to fill them with averages  

In [9]:
for i in li[:7]:
    for c in columns_num:
        print(i[:-4],' ',c,' ',(lis_data[int(i[:-4])][c]=='None').sum())


1   1   27
1   2   31
1   3   27
1   4   27
2   1   29
2   2   24
2   3   19
2   4   18
3   1   25
3   2   25
3   3   25
3   4   25
4   1   10
4   2   10
4   3   11
4   4   12
5   1   45
5   2   43
5   3   94
5   4   39
6   1   6
6   2   6
6   3   6
6   4   7
7   1   22
7   2   18
7   3   16
7   4   17


In [10]:
for i in li[7:]:
    for c in columns_num:
        print(i[:-4],' ',c,' ',(lis_data[int(i[:-4])][c]=='None').sum())


8   1   22
8   2   21
8   3   19
8   4   19
90   1   2
90   2   2
90   3   2
90   4   3
91   1   2
91   2   1
91   3   1
91   4   2
92   1   30
92   2   22
92   3   21
92   4   21
93   1   12
93   2   13
93   3   10
93   4   10
94   1   127
94   2   195
94   3   86
94   4   68


In [11]:
len_data=0
for i in lis_data:
    len_data+=len(lis_data[i])

In [12]:

len_data

10230

In [13]:
for i in lis_data:
    for j in columns_num:
        lis_data[i][j]=pd.to_numeric(lis_data[i][j],errors='coerce')

In [14]:
for i in lis_data:
    for j in columns_num:
        mean=lis_data[i][j].mean()
        lis_data[i][j].fillna(value=mean, inplace=True)


In [15]:
x_batches=[]
y_batches=[]
for i in lis_data:
    for j in range(len(lis_data[i])-25):
        x_batches.append(lis_data[i][j:j+25].to_numpy().astype(np.float64))
        y_batches.append(lis_data[i][j+25:j+26].to_numpy().astype(np.float64))
x_batches=np.array(x_batches)
y_batches=np.array(y_batches)        
  

In [16]:
x_batches_us,y_batches_us=x_batches,y_batches

In [17]:
x_batches,y_batches=shuffle(x_batches,y_batches)

In [18]:
x_batches[0],y_batches[0]

(array([[ 58.71, 143.04,  52.77,   3.32],
        [ 77.13, 166.51,  58.04,   2.54],
        [ 71.39, 163.49,  60.72,   3.99],
        [ 68.53, 146.9 ,  55.54,   3.55],
        [ 72.06, 165.29,  74.99,   5.01],
        [ 75.25, 167.15,  60.43,   2.51],
        [ 74.92, 173.27,  69.06,   4.88],
        [ 74.92, 164.36,  56.5 ,   4.72],
        [ 70.22, 145.24,  37.54,   2.77],
        [ 71.95, 157.28,  53.18,   3.97],
        [ 58.07, 156.95,  70.99,   5.18],
        [ 65.16, 165.59,  73.16,   3.81],
        [ 62.69, 173.98,  68.  ,   4.59],
        [ 64.28, 175.75,  60.86,   4.32],
        [ 69.38, 168.6 ,  57.79,   3.75],
        [ 74.29, 173.2 ,  55.7 ,   3.07],
        [ 62.26, 134.81,  43.05,   2.13],
        [ 52.85, 135.12,  39.73,   1.23],
        [ 57.16, 140.58,  50.45,   3.16],
        [ 57.16, 130.09,  53.51,   2.17],
        [ 43.31, 116.75,  41.66,   2.07],
        [ 28.66,  77.58,  39.79,   0.8 ],
        [ 43.54, 117.78,  50.15,   2.07],
        [ 36.12,  93.85,  42.53,  

In [18]:
# !pip install tensorflow==2.10.1

In [19]:
len(x_batches)

9905

In [21]:
from tensorflow.keras import layers
import tensorflow as tf
from tensorflow import keras
# @tf.function
class TransformerBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super().__init__()
        self.att = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = keras.Sequential(
            [layers.Dense(ff_dim, activation="relu"), layers.Dense(embed_dim),]
        )
        self.layernorm1 = layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = layers.Dropout(rate)
        self.dropout2 = layers.Dropout(rate)

    def call(self, inputs, training):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)
    
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, maxlen,vocab_size, embed_dim):
        super().__init__()
        self.token_emb = layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)
        self.pos_emb = layers.Embedding(input_dim=maxlen, output_dim=embed_dim)
        

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

vocab_size = 1000  
maxlen = 100
embed_dim = 16
num_heads = 6
ff_dim = 256

inputs = layers.Input(shape=(maxlen,))
embedding_layer = TokenAndPositionEmbedding(maxlen, vocab_size, embed_dim)
x = embedding_layer(inputs)
transformer_block1 = TransformerBlock(embed_dim, num_heads, ff_dim)
transformer_block2 = TransformerBlock(embed_dim, num_heads, ff_dim)
transformer_block3 = TransformerBlock(embed_dim, num_heads, ff_dim)

x = transformer_block1(x)
# x = transformer_block2(x)
# x = transformer_block3(x)

x = layers.GlobalAveragePooling1D()(x)
# x = layers.Dense(512, activation="relu")(x)
# x = layers.Dense(256, activation="relu")(x)
x = layers.Dense(256, activation="relu")(x)
x = layers.Dense(256, activation="relu")(x)
x = layers.Dense(128, activation="relu")(x)
outputs = layers.Dense(4)(x)

model = keras.Model(inputs=inputs, outputs=outputs)


model.compile(optimizer="adam", loss="mae", metrics=['mse'])


print(model.summary())

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 100)]             0         
                                                                 
 token_and_position_embeddin  (None, 100, 16)          17600     
 g_1 (TokenAndPositionEmbedd                                     
 ing)                                                            
                                                                 
 transformer_block (Transfor  (None, 100, 16)          14976     
 merBlock)                                                       
                                                                 
 global_average_pooling1d (G  (None, 16)               0         
 lobalAveragePooling1D)                                          
                                                                 
 dense_6 (Dense)             (None, 256)               4352  

In [22]:
x_train=x_batches[:int((0.8)*len(x_batches))]
y_train=y_batches[:int((0.8)*len(y_batches))]
x_test=x_batches[int((0.8)*len(x_batches)):]
y_test=y_batches[int((0.8)*len(y_batches)):]

In [23]:
x_train=np.reshape(x_train,(-1,100))
x_test=np.reshape(x_test,(-1,100))

In [24]:
y_train=np.reshape(y_train,(-1,4))
y_test=np.reshape(y_test,(-1,4))

In [28]:
history = model.fit(
    x_train, y_train, batch_size=64, epochs=20
)

# history = model.fit(x_train, y_train, epochs=20, batch_size=64,
#           use_multiprocessing=True, 
#           **{'function': tf.function(experimental_relax_shapes=True)})


Epoch 1/5
124/124 [==============================] - 1s 11ms/step - loss: 7.7197 - mse: 157.6508
Epoch 2/5
124/124 [==============================] - 1s 10ms/step - loss: 7.5883 - mse: 151.1805
Epoch 3/5
124/124 [==============================] - 1s 10ms/step - loss: 7.4102 - mse: 144.4855
Epoch 4/5
124/124 [==============================] - 1s 10ms/step - loss: 7.2682 - mse: 139.7278
Epoch 5/5
124/124 [==============================] - 1s 10ms/step - loss: 7.2092 - mse: 137.4872


In [29]:
pred=model.predict(x_test)

62/62 [==============================] - 0s 4ms/step


In [30]:
y_test[3],pred[3]

(array([ 65.64, 144.64,  57.33,   3.93]),
 array([ 45.69523  , 100.53379  ,  50.2126   ,   2.7808444], dtype=float32))

In [31]:
from sklearn.metrics import r2_score

r2_score(y_test,pred)

0.7140798536248392

In [32]:
def calculate_aqi(pm25, pm10, no2, so2):
    # Calculate the AQI for each pollutant
    pm25 = pd.to_numeric(pm25)
    pm10 = pd.to_numeric(pm10)
    # o3 = pd.to_numeric(o3)
    no2 = pd.to_numeric(no2)
    so2 = pd.to_numeric(so2)
    # co = pd.to_numeric(co)
    
    aqi_pm25 = 0
    if 0 <= pm25 <= 12:
        aqi_pm25 = 50 * pm25 / 12
    elif 12 < pm25 <= 35.4:
        aqi_pm25 = 50 + 50 * (pm25 - 12) / 23.4
    elif 35.4 < pm25 <= 55.4:
        aqi_pm25 = 100 + 50 * (pm25 - 35.4) / 20
    elif 55.4 < pm25 <= 150.4:
        aqi_pm25 = 150 + 50 * (pm25 - 55.4) / 95
    elif 150.4 < pm25 <= 250.4:
        aqi_pm25 = 200 + 100 * (pm25 - 150.4) / 100
    elif 250.4 < pm25 <= 350.4:
        aqi_pm25 = 300 + 100 * (pm25 - 250.4) / 100
    elif 350.4 < pm25 <= 500.4:
        aqi_pm25 = 400 + 100 * (pm25 - 350.4) / 150

    aqi_pm10 = 0
    if 0 <= pm10 <= 54:
        aqi_pm10 = 50 * pm10 / 54
    elif 54 < pm10 <= 154:
        aqi_pm10 = 50 + 50 * (pm10 - 54) / 100
    elif 154 < pm10 <= 254:
        aqi_pm10 = 100 + 50 * (pm10 - 154) / 100
    elif 254 < pm10 <= 354:
        aqi_pm10 = 150 + 50 * (pm10 - 254) / 100
    elif 354 < pm10 <= 424:
        aqi_pm10 = 200 + 100 * (pm10 - 354) / 70
    elif 424 < pm10 <= 504:
        aqi_pm10 = 300 + 100 * (pm10 - 424) / 80
    elif 504 < pm10 <= 604:
        aqi_pm10 = 400 + 100 * (pm10 - 504) / 100
    aqi_no2 = 0
    if 0 <= no2 <= 0.053:
        aqi_no2 = 50 * no2 / 0.053
    elif 0.053 < no2 <= 0.100:
        aqi_no2 = 50 + 50 * (no2 - 0.053) / 0.047
    elif 0.100 < no2 <= 0.360:
        aqi_no2 = 100 + 50 * (no2 - 0.100) / 0.260
    elif 0.360 < no2 <= 0.649:
        aqi_no2 = 150 + 50 * (no2 - 0.360) / 0.289
    elif 0.649 < no2 <= 1.249:
        aqi_no2 = 200 + 100 * (no2 - 0.649) / 0.600
    elif 1.249 < no2 <= 1.649:
        aqi_no2 = 300 + 100 * (no2 - 1.249) / 0.400
    elif 1.649 < no2 <= 2.049:
        aqi_no2 = 400 + 100 * (no2 - 1.649) / 0.400

    aqi_so2 = 0
    if 0 <= so2 <= 0.035:
        aqi_so2 = 50 * so2 / 0.035
    elif 0.035 < so2 <= 0.075:
        aqi_so2 = 50 + 50 * (so2 - 0.035) / 0.040
    elif 0.075 < so2 <= 0.185:
        aqi_so2 = 100 + 50 * (so2 - 0.075) / 0.110
    elif 0.185 < so2 <= 0.304:
        aqi_so2 = 150 + 50 * (so2 - 0.185) / 0.119
    elif 0.304 < so2 <= 0.604:
        aqi_so2 = 200 + 100 * (so2 - 0.304) / 0.300
    elif 0.604 < so2 <= 0.804:
        aqi_so2 = 300 + 100 * (so2 - 0.604) / 0.200
    elif 0.804 < so2 <= 1.004:
        aqi_so2 = 400 + 100 * (so2 - 0.804) / 0.200
    return int(round(max(aqi_pm25, aqi_pm10, aqi_no2, aqi_so2)))

In [67]:
y_test_aqi=np.zeros(len(y_test))
pred_aqi=np.zeros(len(pred))
for i in range(len(y_test)):
    pred_aqi[i]=calculate_aqi(pred[i][0],pred[i][1],pred[i][2],pred[i][3])
    y_test_aqi[i]=calculate_aqi(y_test[i][0],y_test[i][1],y_test[i][2],y_test[i][3])

In [39]:
window=lis_data[1][-25:].to_numpy().astype(np.float32)

In [44]:
window

array([[ 72.07, 139.61,   6.28,  13.09,  66.64, 135.76,   4.49,  12.39,
         63.18, 147.16,   7.93,  15.81,  52.28, 139.7 ,  12.12,  37.76,
         61.45, 142.04,  15.92,  41.46,  63.79, 148.4 ,   8.9 ,  45.31,
         46.08, 131.79,   2.9 ,  14.72,  52.88, 122.9 ,   4.34,  31.61,
         55.62, 135.76,   8.66,  30.67,  54.57, 142.16,   7.84,  48.25,
         56.  , 144.63,   9.28,  49.62,  61.87, 141.97,  12.13,  27.99,
         52.16, 104.07,   3.73,  19.83,  66.79, 150.36,   6.46,  17.02,
         65.67, 145.24,   8.11,  12.53,  60.82, 145.05,   5.19,  18.14,
         68.97, 154.45,   8.01,  21.93,  73.84, 158.36,   9.08,  35.4 ,
         71.7 , 155.82,  10.77,  36.64,  61.49, 130.93,   7.65,  18.78,
         58.94, 125.91,   4.09,  18.47,  51.69, 109.53,   4.58,  11.71,
         56.56, 123.68,   5.5 ,  10.2 ,  65.25, 135.06,   7.1 ,  12.  ,
         75.41, 159.06,   8.15,  19.41]], dtype=float32)

In [41]:
window=np.reshape(window,(-1,100))

In [45]:
window.shape

(1, 100)

In [58]:
a=model.predict(window)

1/1 [==============================] - 0s 26ms/step


(1, 4)

In [74]:
def aqi_preds(x):
    y = []
    for i in range(59):
        temp = model.predict(x.reshape(1,100), verbose=0)
        x=x[:,4:]
        x=np.append(x,temp).reshape(1,100)
        y.append(temp)
    return y

In [75]:
y=aqi_preds(window)

In [103]:
y_aqi=np.zeros(len(y))
# pred_aqi=np.zeros(len(pred))
for i in range(len(y)):
    a=calculate_aqi(y[i][0][0],y[i][0][1],y[i][0][2],y[i][0][3])
    y_aqi[i]=a
    # y_test_aqi[i]=calculate_aqi(y_test[i][0],y_test[i][1],y_test[i][2],y_test[i][3])

In [104]:
y_aqi

array([158., 155., 151., 151., 149., 153., 151., 148., 149., 151., 152.,
       155., 155., 156., 154., 152., 153., 157., 156., 156., 156., 158.,
       159., 158., 158., 156., 156., 155., 154., 154., 155., 155., 147.,
       138., 138., 136., 150., 151., 151., 149., 142., 141., 140., 140.,
       141., 142., 141., 145., 147., 145., 145., 132., 130., 137., 136.,
       140., 142., 144., 133.])

In [105]:
dum=y_aqi.astype(np.int32)


In [108]:
mar_avg=np.average(dum[:28])
apr_avg=np.average(dum[28:])

In [109]:
mar_avg,apr_avg

(154.21428571428572, 143.25806451612902)

In [110]:
dum[:28],dum[28:]

(array([158, 155, 151, 151, 149, 153, 151, 148, 149, 151, 152, 155, 155,
        156, 154, 152, 153, 157, 156, 156, 156, 158, 159, 158, 158, 156,
        156, 155], dtype=int32),
 array([154, 154, 155, 155, 147, 138, 138, 136, 150, 151, 151, 149, 142,
        141, 140, 140, 141, 142, 141, 145, 147, 145, 145, 132, 130, 137,
        136, 140, 142, 144, 133], dtype=int32))

In [111]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_test,pred)

7.70735564864528

In [112]:
model.save('AQI_Model')

Mounted at /content/drive
